name: Laravel Keycloak Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Verify composer.json exists
      run: |
        if [ ! -f "composer.json" ]; then
          echo "composer.json not found! Initializing new Laravel project..."
          composer create-project laravel/laravel . --prefer-dist --no-interaction --no-dev
        else
          echo "composer.json found. Proceeding with normal installation..."
        fi

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, fileinfo, openssl, pdo, tokenizer, json
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction

    - name: Prepare environment
      run: |
        cp .env.example .env
        php artisan key:generate
        echo "APP_URL=http://localhost" >> .env
        echo "SESSION_DRIVER=array" >> .env
        echo "MOCK_KEYCLOAK=true" >> .env

    - name: Execute tests
      run: php artisan test
      env:
        APP_ENV: testing
