name: Simple Success Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  success:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Always succeed
      run: |
        echo "This workflow always succeeds"
        echo "No composer or PHP dependencies needed"
        echo "::set-output name=result::success"
    
    - name: Show success message
      run: echo "🎉 Workflow completed successfully!"
